new updates in README.md file
hrb1989/devops23-jun pull request #2
Opened 2021-06-25 11:04 UTC by hrb1989

new updates in README.md file

2021-06-25 11:07 UTC, mahojase requested changes

2021-06-25 11:07 UTC, mahojase commented on README.md
> +New update
what is this new update?

2021-06-25 11:08 UTC, hrb1989 commented on README.md
> +New update
this is for the learning repository PR.

2021-06-25 11:09 UTC, mahojase approved these changes

2021-06-25 11:12 UTC, merged

2021-06-30 10:10 UTC, muralik25 commented
ok